project:
  type: book
  output-dir: docs

execute: 
  echo: false
  warning: false
  message: false

book:
  title: "PPLE Skills and Research Methods for Psychology: tutorial manual"
  author: "David Fleming"
  license: "CC BY-SA"
  page-footer: CC-BY-SA-4.0 (2025) David Fleming
  repo-url: https://github.com/dvlaming/SRMP
  repo-actions: [issue, source]
  chapters:
    - index.qmd
    - t1.qmd
    - t2.qmd
    - t3.qmd
    - references.qmd
  appendices: 
    - a1.qmd
    - a2.qmd

bibliography: references.bib
csl: apa-annotated-bibliography.csl
format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

