project:
  type: book
  output-dir: docs

book:
  title: "SRMP tutorials"
  author: "David Fleming"
  license: "CC BY-SA"
  page-footer: CC-BY-SA-4.0 (2025) David Fleming
  repo-url: https://github.com/dvlaming/SRMP
  repo-actions: [issue, source]
  chapters:
    - index.qmd
    - t1.qmd
    - t2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

